// Generated by CoffeeScript 1.7.1
var toggleDrawer;

toggleDrawer = function() {
  var drawer_panel;
  drawer_panel = document.querySelector('core-drawer-panel');
  return drawer_panel.togglePanel();
};
